# Generated by Django 4.2.18 on 2025-02-03 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemShopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('already_bought', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application1.item')),
            ],
        ),
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoplist_name', models.CharField(max_length=20)),
                ('items', models.ManyToManyField(through='Application1.ItemShopList', to='Application1.item')),
            ],
        ),
        migrations.AddField(
            model_name='itemshoplist',
            name='shop_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application1.shoplist'),
        ),
    ]
